import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
//components
import Calendar from "@/components/Calendar/Calendar";
import DarkModeButton from "@/components/DarkModeButton/DarkModeButton";
//icons

//hooks
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  
  return (
    <>
      <Head>
        <title>Calendar One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/calendar-svgrepo-com.svg" />
      </Head>
      <main
        className={`${styles.main} ${inter.className}`}
        data-theme={darkMode && "dark"}
      >
        <div className={styles.calendar_wrapper}>
          <Calendar />
        </div>

        <DarkModeButton darkMode={darkMode} setDarkMode={setDarkMode} />

       
      </main>
    </>
  );
}
